pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  outputDirectory: '$(System.DefaultWorkingDirectory)/ModuleOutput/LWM.WakeOnLan'

steps:
- checkout: self
  fetchDepth: 0

# Set up .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'

# Restore NuGet packages
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: $(solution)

# GitVersion setup and execution
- task: gitversion/setup@3
  displayName: 'Setup GitVersion'
  inputs:
    versionSpec: '5.10.3'

- task: gitversion/execute@3
  displayName: 'Run GitVersion'
  inputs:
    configFilePath: 'gitversion.yml'
    updateAssemblyInfo: true

# Build the solution
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Configuration=$(buildConfiguration) /p:OutputPath=$(outputDirectory)/bin /p:Version=$(GitVersion.FullSemVer)'
    configuration: '$(buildConfiguration)'
    platform: '$(buildPlatform)'

# Publish the entire ModuleOutput/LWM.WakeOnLan directory
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(outputDirectory)'
    ArtifactName: 'WakeOnLanModule'
