trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  outputPath: 'ModuleOutput/LWM.WakeOnLan/bin'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: $(solution)

# GitVersion setup and usage
- task: gitversion/setup@3
  displayName: 'Setup GitVersion'

- script: gitversion /config gitversion.yml
  displayName: 'Run GitVersion'
  continueOnError: false

- script: |
    echo ##vso[task.setvariable variable=GitVersion.FullSemVer]$(GitVersion.FullSemVer)
  displayName: 'Extract GitVersion Variables'

# Build the solution using GitVersion versioning
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Configuration=$(buildConfiguration) /p:OutputPath=$(outputPath) /p:Version=$(GitVersion.FullSemVer)'
    platform: '$(buildConfiguration)'

# Publish artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(outputPath)
    ArtifactName: 'Module'
