pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  outputPath: 'ModuleOutput/LWM.WakeOnLan/bin'

steps:
# Checkout with full history
- checkout: self
  fetchDepth: 0

# Set up .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'

# Restore NuGet packages
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: $(solution)

# GitVersion setup and execution
- task: gitversion/setup@3
  displayName: 'Setup GitVersion'
  inputs:
    versionSpec: '5.10.3' # Specify a compatible version

- task: gitversion/execute@3
  displayName: 'Run GitVersion'
  inputs:
    configFilePath: 'gitversion.yml' # Use custom GitVersion configuration
    updateAssemblyInfo: true        # Automatically update assembly info

# Extract GitVersion variables
- script: |
    echo ##vso[task.setvariable variable=GitVersion.FullSemVer]$(GitVersion.FullSemVer)
  displayName: 'Extract GitVersion Variables'

# Build the solution using GitVersion versioning
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Configuration=$(buildConfiguration) /p:OutputPath=$(outputPath) /p:Version=$(GitVersion.FullSemVer)'
    platform: '$(buildConfiguration)'

# Publish artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(outputPath)
    ArtifactName: 'Module'
