pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU' # Specify a valid platform
  outputPath: 'ModuleOutput/LWM.WakeOnLan/bin'

steps:
- checkout: self
  fetchDepth: 0

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: $(solution)

# GitVersion setup and execution
- task: gitversion/setup@3
  displayName: 'Setup GitVersion'
  inputs:
    versionSpec: '5.10.3'

- task: gitversion/execute@3
  displayName: 'Run GitVersion'
  inputs:
    configFilePath: 'gitversion.yml'
    updateAssemblyInfo: true

- script: |
    echo ##vso[task.setvariable variable=GitVersion.FullSemVer]$(GitVersion.FullSemVer)
  displayName: 'Extract GitVersion Variables'

# Build the solution using GitVersion versioning
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:Configuration=$(buildConfiguration) /p:OutputPath=$(outputPath) /p:Version=$(GitVersion.FullSemVer)'
    configuration: '$(buildConfiguration)'
    platform: '$(buildPlatform)'

# Publish artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(outputPath)
    ArtifactName: 'Module'
