####################################################
#          ModuleBuilder Configuration             #
####################################################

BuiltModuleSubdirectory: module
VersionedOutputDirectory: true

BuildWorkflow:
  ".": # Default workflow
    - clean
    - build

  build:
    - clean
    - restore
    - Build_Module_ModuleBuilder
    - compile
    - Create_changelog_release_output

  test:
    - clean
    - restore
    - compile
    - pester_tests

  pack:
    - build
    - package_module_nupkg

  publish:
    - Publish_Release_To_GitHub # Runs first, if token is expired it will fail early
    - publish_module_to_gallery

RequiredModulesDirectory: output/RequiredModules



ModuleBuildTasks:
  Sampler:
    - "*.build.Sampler.ib.tasks"
  Sampler.GitHubTasks:
    - "*.ib.tasks"

TaskHeader: |
  param($Path)
  ""
  "=" * 79
  Write-Build Cyan "`t`t`t$($Task.Name.replace("_"," ").ToUpper())"
  Write-Build DarkGray  "$(Get-BuildSynopsis $Task)"
  "-" * 79
  Write-Build DarkGray "  $Path"
  Write-Build DarkGray "  $($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
  ""

GitHubConfig:
  GitHubFilesToAdd:
    - "CHANGELOG.md"
  GitHubConfigUserName: LarryWisherMan
  GitHubConfigUserEmail: MikeRow@upkep.net
  UpdateChangelogOnPrerelease: false
