//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("WakeOnLanLibrary")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersion("0.2.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.2.0-preview0001+Sha.045a78eaec8e14a0c558c4223d13ee2d59a6532e.Date.2025-01-03")]
[assembly: System.Reflection.AssemblyProductAttribute("WakeOnLanLibrary")]
[assembly: System.Reflection.AssemblyTitleAttribute("WakeOnLanLibrary")]
[assembly: System.Reflection.AssemblyVersion("0.2.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

