#
# Module manifest for module 'LWM.WakeOnLan'
#
# Generated by: LarryWisherMan
#
# Generated on: 12/27/2024
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'WakeOnLanCmdlets.dll'

    # Version number of this module.
    ModuleVersion     = '0.0.1'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID              = '6b3e70ff-5a28-4fb5-a9ec-7a07a54bf907'

    # Author of this module
    Author            = 'LarryWisherMan'

    # Company or vendor of this module
    CompanyName       = 'LarryWisherMan'

    # Copyright statement for this module
    Copyright         = '(c) LarryWisherMan. All rights reserved.'

    # Description of the functionality provided by this module
Description = @"
LWM.WakeOnLan is a PowerShell module designed to facilitate sending Wake-on-LAN (WOL) requests and managing the status of target computers.
It supports scenarios such as sending WOL requests across subnets using proxy computers, monitoring the status of target machines after WOL requests,
and retrieving detailed logs of operations. The module integrates seamlessly with PowerShell for easy automation and scripting,
making it ideal for administrators managing remote infrastructure.
"@

    # Minimum version of the PowerShell engine required by this module
     PowerShellVersion = '5.1'

    # Name of the PowerShell host required by this module
     #PowerShellHostName = '*'

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
     DotNetFrameworkVersion = '4.7.2'

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
     ClrVersion = '4.0'

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Assemblies that must be loaded prior to importing this module
 RequiredAssemblies = @(
        'Microsoft.Extensions.DependencyInjection.dll',
        'Microsoft.Extensions.DependencyInjection.Abstractions.dll',
        'Microsoft.Extensions.Options.dll',
        'Microsoft.Bcl.AsyncInterfaces.dll',
        'System.Runtime.CompilerServices.Unsafe.dll',
        'System.Threading.Tasks.Extensions.dll',
        'WakeOnLanLibrary.dll'
    )

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = '*'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = '*'

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = '*'

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @(
                'WakeOnLan',
                'Networking',
                'Automation',
                'PowerShell',
                'RemoteManagement',
                'WOL',
                'NetworkTools',
                'SystemAdministration',
                'Infrastructure'
            )

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
             ProjectUri = 'https://github.com/LarryWisherMan/WakeOnLan'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
             ReleaseNotes = ''

            # Prerelease string of this module
             Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''


}
